version: 0.2
phases:
  install:
    commands:
      - if not exist C:\ProgramData\chocolatey\bin\choco.exe (
          @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command " [System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
        )
      - choco install dotnet-4.8 -y
  build:
    commands:
      - echo "Building the application..."
      - msbuild HelloWorldDotNetFramework.sln /p:Configuration=Release
artifacts:
  files:
    - '**/*'
  discard-paths: yes
