version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1  # Ensure this is set to ap-south-1 for artifact uploads
    CODEBUILD_BUILD_REGION: ap-south-1  # For the artifact upload phase to be region-correct

phases:
  install:
    runtime-versions:
      dotnet: 4.8
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the .NET project..."
      - msbuild HelloWorldDotNetFramework.sln /p:Configuration=Release

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  name: my-artifact
  s3-bucket: arn:aws:s3::911167891314:accesspoint/ma85pkon3s33y.mrap  # Multi-Region Access Point ARN
  s3-prefix: build
  encryption-disabled: true  # Explicitly set encryption if needed, based on policy
  region: ap-south-1  # Explicitly mention the region for artifact upload
