version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1  # Ensure this matches the region of your S3 bucket

phases:
  install:
    runtime-versions:
      dotnet: 4.8
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the .NET project..."
      - msbuild HelloWorldDotNetFramework.sln /p:Configuration=Release

artifacts:
  files:
    - '**/*'  # Include all files from the build
  discard-paths: yes
  name: my-artifact
  s3-bucket: dotnet12bucket  # Name of the S3 bucket
  s3-prefix: build
  region: ap-south-1  # Correct region for S3 bucket
