version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    
phases:
  install:
    runtime-versions:
      dotnet: 4.8
  build:
    commands:
      - msbuild HelloWorldDotNetFramework.sln /p:Configuration=Release
artifacts:
  files:
    - '**/*'
  name: my-artifact  
  discard-paths: yes
  s3-bucket: dotnet12bucket
  s3-prefix: build
  s3-region: ap-south-1  # This is the region for Mumbai
