version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1  # Since CodeBuild is running in us-east-1

phases:
  install:
    runtime-versions:
      dotnet: 4.8
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the .NET project..."
      - msbuild HelloWorldDotNetFramework.sln /p:Configuration=Release

artifacts:
  files:
    - '**/*'  # Include all files from the build
  discard-paths: yes
  name: my-artifact
  s3-bucket: arn:aws:s3::911167891314:accesspoint/ma85pkon3s33y.mrap  # Use the Multi-Region Access Point ARN
  s3-prefix: build
